"""empty message

Revision ID: 09505029ab5a
Revises: 4328da54c4e1
Create Date: 2020-10-17 15:59:03.085990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09505029ab5a'
down_revision = '4328da54c4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_hist_evento',
    sa.Column('id_hist_evento', sa.Integer(), nullable=False),
    sa.Column('cd_processo', sa.String(length=50), nullable=False),
    sa.Column('cd_classe_judicial', sa.String(length=20), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('dt_ocorrencia', sa.Time(), nullable=False),
    sa.Column('ind_ri', sa.String(length=1), nullable=False),
    sa.Column('nu_autuacao', sa.Integer(), nullable=False),
    sa.Column('sg_tribunal', sa.String(length=30), nullable=False),
    sa.Column('sg_grau', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['tb_desc_evento.id_evento'], ),
    sa.PrimaryKeyConstraint('id_hist_evento')
    )
    op.drop_table('tb_hist_movimento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_hist_movimento',
    sa.Column('id_hist_movimento', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cd_processo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cd_classe_judicial', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id_movimento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dt_ocorrencia', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('ind_ri', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('nu_autuacao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sg_tribunal', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('sg_grau', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_movimento'], ['tb_desc_movimento.id_movimento'], name='tb_hist_movimento_id_movimento_fkey'),
    sa.PrimaryKeyConstraint('id_hist_movimento', name='tb_hist_movimento_pkey')
    )
    op.drop_table('tb_hist_evento')
    # ### end Alembic commands ###
