"""Criação de tabelas utilizadas no fluxo

Revision ID: 1f5b66bd7fd4
Revises: f9f9f05e7bf5
Create Date: 2020-10-17 15:24:57.556380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5b66bd7fd4'
down_revision = 'f9f9f05e7bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_hist_movimento',
                    sa.Column('id_hist_movimento',
                              sa.Integer(), nullable=False),
                    sa.Column('cd_processo', sa.String(
                        length=50), nullable=False),
                    sa.Column('cd_classe_judicial', sa.String(
                        length=20), nullable=False),
                    sa.Column('id_movimento', sa.Integer(), nullable=False),
                    sa.Column('dt_ocorrencia', sa.Time(), nullable=False),
                    sa.Column('ind_ri', sa.String(length=1), nullable=False),
                    sa.Column('nu_autuacao', sa.Integer(), nullable=False),
                    sa.Column('sg_tribunal', sa.String(
                        length=30), nullable=False),
                    sa.Column('sg_grau', sa.String(length=30), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id_movimento'], ['tb_desc_movimento.id_movimento'], ),
                    sa.PrimaryKeyConstraint('id_hist_movimento')
                    )
    op.create_table('tb_hist_situacao',
                    sa.Column('id_hist_situacao',
                              sa.Integer(), nullable=False),
                    sa.Column('cd_processo', sa.String(
                        length=50), nullable=False),
                    sa.Column('cd_classe_judicial', sa.String(
                        length=20), nullable=False),
                    sa.Column('nu_autuacao', sa.Integer(), nullable=False),
                    sa.Column('id_situacao_origem',
                              sa.Integer(), nullable=False),
                    sa.Column('id_situacao_destino',
                              sa.Integer(), nullable=False),
                    sa.Column('id_movimento', sa.Integer(), nullable=False),
                    sa.Column('dt_ocorrencia', sa.Time(), nullable=False),
                    sa.Column('ind_valida', sa.String(
                        length=1), nullable=False),
                    sa.Column('ind_consistente', sa.String(
                        length=1), nullable=False),
                    sa.Column('ind_efetiva', sa.String(
                        length=1), nullable=False),
                    sa.Column('sg_tribunal', sa.String(
                        length=30), nullable=False),
                    sa.Column('sg_grau', sa.String(length=30), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id_movimento'], ['tb_desc_movimento.id_movimento'], ),
                    sa.ForeignKeyConstraint(['id_situacao_destino'], [
                        'tb_desc_situacao.id_situacao'], ),
                    sa.ForeignKeyConstraint(['id_situacao_origem'], [
                        'tb_desc_situacao.id_situacao'], ),
                    sa.PrimaryKeyConstraint('id_hist_situacao')
                    )
    op.add_column('tb_desc_grp_situacao', sa.Column(
        'sg_grau', sa.String(length=30), nullable=False))
    op.add_column('tb_desc_grp_situacao', sa.Column(
        'sg_tribunal', sa.String(length=30), nullable=False))
    op.add_column('tb_desc_situacao', sa.Column(
        'sg_grau', sa.String(length=30), nullable=False))
    op.add_column('tb_desc_situacao', sa.Column(
        'sg_tribunal', sa.String(length=30), nullable=False))
    op.add_column('tb_fluxo', sa.Column(
        'sg_grau', sa.String(length=30), nullable=False))
    op.add_column('tb_fluxo', sa.Column(
        'sg_tribunal', sa.String(length=30), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_fluxo', 'sg_tribunal')
    op.drop_column('tb_fluxo', 'sg_grau')
    op.drop_column('tb_desc_situacao', 'sg_tribunal')
    op.drop_column('tb_desc_situacao', 'sg_grau')
    op.drop_column('tb_desc_grp_situacao', 'sg_tribunal')
    op.drop_column('tb_desc_grp_situacao', 'sg_grau')
    op.drop_table('tb_hist_situacao')
    op.drop_table('tb_hist_movimento')    
