"""Correção do relacionamento entre movimento e complemento

Revision ID: 34b44946528d
Revises: 1f5b66bd7fd4
Create Date: 2020-10-17 15:46:10.232910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b44946528d'
down_revision = '1f5b66bd7fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_desc_complemento',
    sa.Column('id_complemento', sa.Integer(), nullable=False),
    sa.Column('ds_complemento', sa.String(length=255), nullable=False),
    sa.Column('cd_tpu_complemento', sa.String(length=50), nullable=False),
    sa.Column('vl_complemento', sa.String(length=30), nullable=False),
    sa.Column('id_movimento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_movimento'], ['tb_desc_movimento.id_movimento'], ),
    sa.PrimaryKeyConstraint('id_complemento')
    )
    op.drop_column('tb_desc_movimento', 'cd_tpu_complemento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_desc_movimento', sa.Column('cd_tpu_complemento', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_table('tb_desc_complemento')
    # ### end Alembic commands ###
