"""empty message

Revision ID: 391c8106a2e4
Revises: e12ac7121796
Create Date: 2020-10-17 18:15:36.863545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391c8106a2e4'
down_revision = 'e12ac7121796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_fluxo', sa.Column('ind_fluxo_ri', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_fluxo', 'ind_fluxo_ri')
    # ### end Alembic commands ###
