"""empty message

Revision ID: 394f670c059c
Revises: 09505029ab5a
Create Date: 2020-10-17 17:16:46.091668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394f670c059c'
down_revision = '09505029ab5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_desc_evento', sa.Column('cd_evento', sa.String(length=30), nullable=False))
    op.drop_column('tb_desc_movimento', 'ds_movimento')
    op.drop_column('tb_desc_movimento', 'sg_movimento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_desc_movimento', sa.Column('sg_movimento', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('tb_desc_movimento', sa.Column('ds_movimento', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('tb_desc_evento', 'cd_evento')
    # ### end Alembic commands ###
