"""empty message

Revision ID: 3e99712adbee
Revises: 394f670c059c
Create Date: 2020-10-17 17:37:33.682776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e99712adbee'
down_revision = '394f670c059c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_desc_movimento_id_evento_fkey', 'tb_desc_movimento', type_='foreignkey')
    op.create_foreign_key(None, 'tb_desc_movimento', 'tb_desc_evento', ['id_evento'], ['id_evento'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_desc_movimento', type_='foreignkey')
    op.create_foreign_key('tb_desc_movimento_id_evento_fkey', 'tb_desc_movimento', 'tb_desc_movimento', ['id_evento'], ['id_movimento'])
    # ### end Alembic commands ###
