"""empty message

Revision ID: 4328da54c4e1
Revises: 34b44946528d
Create Date: 2020-10-17 15:57:31.116459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4328da54c4e1'
down_revision = '34b44946528d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_desc_evento',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('ds_evento', sa.String(length=255), nullable=False),
    sa.Column('ind_fluxo_ri', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.add_column('tb_desc_movimento', sa.Column('id_evento', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tb_desc_movimento', 'tb_desc_movimento', ['id_evento'], ['id_movimento'])
    op.add_column('tb_fluxo', sa.Column('id_evento', sa.Integer(), nullable=False))
    op.drop_constraint('tb_fluxo_id_movimento_fkey', 'tb_fluxo', type_='foreignkey')
    op.create_foreign_key(None, 'tb_fluxo', 'tb_desc_evento', ['id_evento'], ['id_evento'])
    op.drop_column('tb_fluxo', 'id_movimento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_fluxo', sa.Column('id_movimento', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tb_fluxo', type_='foreignkey')
    op.create_foreign_key('tb_fluxo_id_movimento_fkey', 'tb_fluxo', 'tb_desc_movimento', ['id_movimento'], ['id_movimento'])
    op.drop_column('tb_fluxo', 'id_evento')
    op.drop_constraint(None, 'tb_desc_movimento', type_='foreignkey')
    op.drop_column('tb_desc_movimento', 'id_evento')
    op.drop_table('tb_desc_evento')
    # ### end Alembic commands ###
