"""Incluindo a data da autuação do processo

Revision ID: 5463259131ec
Revises: 8194edcf5f47
Create Date: 2020-10-18 16:41:06.512275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5463259131ec'
down_revision = '8194edcf5f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_processo', sa.Column('dt_autuacao', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_processo', 'dt_autuacao')
    # ### end Alembic commands ###
