"""Mapeamento das tabelas para persistir os processos datajud

Revision ID: 6fdbb9233bd6
Revises: 8d2eb6149b1d
Create Date: 2020-10-18 09:22:06.650559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdbb9233bd6'
down_revision = '8d2eb6149b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_processo',
    sa.Column('cd_processo', sa.String(length=100), nullable=False),
    sa.Column('nu_processo', sa.String(length=50), nullable=False),
    sa.Column('cd_classe', sa.String(length=50), nullable=False),
    sa.Column('cd_orgao_julgador', sa.String(length=50), nullable=False),
    sa.Column('ds_orgao_julgador', sa.String(length=4000), nullable=False),
    sa.Column('sg_tribunal', sa.String(length=30), nullable=False),
    sa.Column('sg_grau', sa.String(length=30), nullable=False),
    sa.Column('ind_presidencia', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('cd_processo')
    )
    op.create_table('tb_processo_evento',
    sa.Column('id_processo_evento', sa.Integer(), nullable=False),
    sa.Column('dt_ocorrencia', sa.Time(), nullable=False),
    sa.Column('cd_processo', sa.String(length=100), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cd_processo'], ['tb_processo.cd_processo'], ),
    sa.ForeignKeyConstraint(['id_evento'], ['tb_desc_evento.id_evento'], ),
    sa.PrimaryKeyConstraint('id_processo_evento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_processo_evento')
    op.drop_table('tb_processo')
    # ### end Alembic commands ###
