"""Relacionando a situação com o grupo

Revision ID: 8cb2ef1d5d5c
Revises: fdf3fd351567
Create Date: 2020-10-19 19:16:05.426824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb2ef1d5d5c'
down_revision = 'fdf3fd351567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_desc_situacao', sa.Column('id_grupo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tb_desc_situacao', 'tb_desc_grp_situacao', ['id_grupo'], ['id_grupo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_desc_situacao', type_='foreignkey')
    op.drop_column('tb_desc_situacao', 'id_grupo')
    # ### end Alembic commands ###
