"""Criamos o tipo especial do evento para tratar (presidência e decisões monocráticas / colegiadas)

Revision ID: 8d2eb6149b1d
Revises: 7ae251e44a17
Create Date: 2020-10-18 08:46:47.017295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2eb6149b1d'
down_revision = '7ae251e44a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_desc_evento', sa.Column('ind_tipo_especial', sa.String(length=1), nullable=True))
    op.execute("""
        update tb_desc_evento set ind_tipo_especial = 'P' where cd_evento in ('DPR','DP', 'ECP', 'CP');
        update tb_desc_evento set ind_tipo_especial = 'C' where cd_evento in ('DCT', 'DCI');
        update tb_desc_evento set ind_tipo_especial = 'M' where cd_evento in ('DMI', 'DMT');        
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_desc_evento', 'ind_tipo_especial')
    # ### end Alembic commands ###
