"""Incluindo a coluna tb_hist_situacao.nu_seq_evento

Revision ID: bd87f0f97703
Revises: 6cf06e62d7be
Create Date: 2020-10-18 17:03:20.623995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd87f0f97703'
down_revision = '6cf06e62d7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_hist_situacao', sa.Column('nu_seq_evento', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_hist_situacao', type_='foreignkey')
    op.drop_column('tb_hist_situacao', 'nu_seq_evento')
    # ### end Alembic commands ###
