"""empty message

Revision ID: e12ac7121796
Revises: 3e99712adbee
Create Date: 2020-10-17 17:40:18.782783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12ac7121796'
down_revision = '3e99712adbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_desc_complemento', 'ds_complemento')
    op.drop_column('tb_desc_complemento', 'vl_complemento')
    op.add_column('tb_desc_complemento', sa.Column('vl_complemento', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_desc_complemento', sa.Column('ds_complemento', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('tb_desc_complemento', 'vl_complemento')
    op.add_column('tb_desc_complemento', sa.Column('vl_complemento', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
