"""empty message

Revision ID: f9f9f05e7bf5
Revises: 
Create Date: 2020-10-16 07:41:13.246107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f9f05e7bf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_desc_grp_situacao',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('ds_grupo', sa.String(length=255), nullable=False),
    sa.Column('cd_grupo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_table('tb_desc_movimento',
    sa.Column('id_movimento', sa.Integer(), nullable=False),
    sa.Column('ds_movimento', sa.String(length=255), nullable=False),
    sa.Column('cd_tpu_movimento', sa.String(length=50), nullable=False),
    sa.Column('sg_movimento', sa.String(length=30), nullable=False),
    sa.Column('cd_tpu_complemento', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_movimento')
    )
    op.create_table('tb_desc_situacao',
    sa.Column('id_situacao', sa.Integer(), nullable=False),
    sa.Column('ds_situacao', sa.String(length=255), nullable=False),
    sa.Column('cd_situacao', sa.String(length=50), nullable=False),
    sa.Column('ind_principal', sa.String(length=1), nullable=False),
    sa.Column('ind_ri', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id_situacao')
    )
    op.create_table('tb_fluxo',
    sa.Column('id_fluxo_movimento', sa.String(length=255), nullable=False),
    sa.Column('id_situacao_origem', sa.Integer(), nullable=False),
    sa.Column('id_movimento', sa.Integer(), nullable=False),
    sa.Column('id_situacao_destino', sa.Integer(), nullable=False),
    sa.Column('ind_consistente', sa.String(length=1), nullable=False),
    sa.Column('ind_efetiva', sa.String(length=1), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_grupo'], ['tb_desc_grp_situacao.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_movimento'], ['tb_desc_movimento.id_movimento'], ),
    sa.ForeignKeyConstraint(['id_situacao_destino'], ['tb_desc_situacao.id_situacao'], ),
    sa.ForeignKeyConstraint(['id_situacao_origem'], ['tb_desc_situacao.id_situacao'], ),
    sa.PrimaryKeyConstraint('id_fluxo_movimento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_fluxo')
    op.drop_table('tb_desc_situacao')
    op.drop_table('tb_desc_movimento')
    op.drop_table('tb_desc_grp_situacao')
    # ### end Alembic commands ###
