"""Incluindo indicadores de situações de início e término do fluxo

Revision ID: fdf3fd351567
Revises: ece4bfaf1f35
Create Date: 2020-10-19 15:39:23.256528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf3fd351567'
down_revision = 'ece4bfaf1f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_desc_situacao', sa.Column('fl_fim', sa.String(length=1), nullable=True))
    op.add_column('tb_desc_situacao', sa.Column('fl_inicio', sa.String(length=1), nullable=True))
    op.create_foreign_key(None, 'tb_hist_situacao', 'tb_desc_situacao', ['id_situacao_origem'], ['id_situacao'])
    op.create_foreign_key(None, 'tb_hist_situacao', 'tb_desc_evento', ['id_evento'], ['id_evento'])
    op.execute("update tb_desc_situacao set fl_fim = 'N' where cd_situacao <> 'ARQ'")
    op.execute("update tb_desc_situacao set fl_fim = 'S' where cd_situacao = 'ARQ'")
    op.execute("update tb_desc_situacao set fl_inicio = 'N' where cd_situacao <> 'I'")
    op.execute("update tb_desc_situacao set fl_inicio = 'S' where cd_situacao = 'I'")
    op.execute("alter table tb_desc_situacao alter column fl_inicio set not null")
    op.execute("alter table tb_desc_situacao alter column fl_fim set not null")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_hist_situacao', type_='foreignkey')
    op.drop_constraint(None, 'tb_hist_situacao', type_='foreignkey')
    op.drop_column('tb_desc_situacao', 'fl_inicio')
    op.drop_column('tb_desc_situacao', 'fl_fim')
    # ### end Alembic commands ###
